Intergation custom table view to vc
igover/CalendarKit pull request #4
Opened 2022-11-01 10:11 UTC by igover

2022-11-01 10:13 UTC, Mishania13 approved these changes

2022-11-01 13:30 UTC, IvanKrim approved these changes

2022-11-02 17:59 UTC, firuz1844 requested changes
Про магические числа на твое усмотрение, но комментарии бы не помешали. К timeOnly и minDate

2022-11-02 17:59 UTC, firuz1844 commented on Sources/Extensions/Date+DateOnly.swift
> +    func timeOnly() -> Float {
честно сказать, так и не понял, что этот метод возвращает... Float... Time... В каких единицах измерения возвращается timeOnly?

2022-11-02 17:59 UTC, firuz1844 commented on Sources/Timeline/TimelineContainer.swift
> +        let timeToScroll = Date().timeOnly() - 4
Тут еще какие-то магические 4 единицы чего-то отнимаются...

2022-11-02 17:59 UTC, firuz1844 commented on Sources/Timeline/TimelineContainer.swift
> +    let bottomOfScrollView = contentSize.height - bounds.size.height + 30
Опять магическая цифра)

2022-11-02 17:59 UTC, firuz1844 commented on Sources/Timeline/TimelinePagerView.swift
> +    public var minDate: Date?
Добавить бы комментарий с описанием, что это за минимальная дата и для чего она используется

2022-11-03 07:34 UTC, JohnnyThompson approved these changes

2022-11-03 10:32 UTC, firuz1844 approved these changes

2022-11-03 10:49 UTC, merged